### ISSUE TITLE
'docker-machine ip default' fails

### ISSUE THREAD

**Issue by raboof** [hseeberger/constructr#48]
When trying to run the tests, I usually get:

```
[info] * de.heikoseeberger.constructr.akka.MultiNodeConsulConstructrSpec
[JVM-5] Error saving host to store: remove /home/aengelen/.docker/machine/machines/default/config.json: no such file or directory
[JVM-5] *** RUN ABORTED ***
[JVM-5]   java.lang.ExceptionInInitializerError:
[JVM-5]   at de.heikoseeberger.constructr.akka.MultiNodeConsulConstructrSpec.<init>(MultiNodeConsulConstructrSpec.scala:67)
[JVM-5]   at de.heikoseeberger.constructr.akka.MultiNodeConsulConstructrSpecMultiJvmNode5.<init>(MultiNodeConsulConstructrSpec.scala:65)
[JVM-5]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-5]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-5]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-5]   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[JVM-5]   at java.lang.Class.newInstance(Class.java:442)
[JVM-5]   at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:2644)
[JVM-5]   at org.scalatest.tools.Runner$$anonfun$37.apply(Runner.scala:2461)
[JVM-5]   at org.scalatest.tools.Runner$$anonfun$37.apply(Runner.scala:2460)
[JVM-5]   ...
[JVM-5]   Cause: java.lang.RuntimeException: Nonzero exit value: 1
[JVM-5]   at scala.sys.package$.error(package.scala:27)
[JVM-5]   at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:132)
[JVM-5]   at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
[JVM-5]   at de.heikoseeberger.constructr.akka.ConsulConstructrMultiNodeConfig$.<init>(MultiNodeConsulConstructrSpec.scala:40)
[JVM-5]   at de.heikoseeberger.constructr.akka.ConsulConstructrMultiNodeConfig$.<clinit>(MultiNodeConsulConstructrSpec.scala)
[JVM-5]   at de.heikoseeberger.constructr.akka.MultiNodeConsulConstructrSpec.<init>(MultiNodeConsulConstructrSpec.scala:67)
[JVM-5]   at de.heikoseeberger.constructr.akka.MultiNodeConsulConstructrSpecMultiJvmNode5.<init>(MultiNodeConsulConstructrSpec.scala:65)
[JVM-5]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[JVM-5]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[JVM-5]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[JVM-5]   ...
```

... which suggests 'docker-machine ip default' fails. The strange thing is it *sometimes* works for the Etcd test.

Running 'docker-machine ip default' on the command-line works fine.

I'm running on Linux

When hard-coding the docker-machine ip the tests run without further problems.

**Comment by hseeberger** [comment]
We definitely need better testing, in particular testing that works on Travis.

**Comment by raboof** [comment]
Agreed. This particular error seems to be an upstream issue though, https://github.com/docker/machine/issues/2612
